### ISSUE TITLE
Review each issue and assess its status

### ISSUE THREAD

**Issue by fjlopez** [sitmun/community#4]
# Features requested

These feature requests  are well described and probably implies an update in three modules back, admin and viewer. 

**Application**:
- https://github.com/sitmun/sitmun-viewer-app/issues/12

**Geographic Information (i.e. Layer)**
- https://github.com/sitmun/sitmun-viewer-app/issues/9

**Task parameters**
JSON as task parameter. Any SITNA task that requires configuration should be fixed with this support
- https://github.com/sitmun/sitmun-backend-core/issues/172
- https://github.com/sitmun/sitmun-viewer-app/issues/15
- https://github.com/sitmun/sitmun-viewer-app/issues/31

**User**
-  https://github.com/sitmun/sitmun-backend-core/issues/143
- https://github.com/sitmun/sitmun-admin-app/issues/155 but it is quite clear the goal

# Confirmed back-end bugs

- [ ] https://github.com/sitmun/sitmun-admin-app/issues/153 (move to sitmun-core-app)

# Bugs to be reviewed

- [x] https://github.com/sitmun/sitmun-admin-app/issues/156
- [x] https://github.com/sitmun/sitmun-admin-app/issues/144
- [x] https://github.com/sitmun/sitmun-admin-app/issues/142
- [x] https://github.com/sitmun/sitmun-admin-app/issues/140

# Technical debt

- [x] https://github.com/sitmun/sitmun-admin-app/issues/131
- [x] https://github.com/sitmun/sitmun-backend-core/issues/173

# Documentation

- [x] https://github.com/sitmun/sitmun-backend-core/issues/176

# Issues closed

- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/132~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/57~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/56~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/55~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/150~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/164~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/158~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/143~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/159~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/152~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/146~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/113~ 
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/149~
- [x] ~https://github.com/sitmun/sitmun-viewer-app/issues/29~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/21~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/145~
- [x] ~https://github.com/sitmun/sitmun-viewer-app/issues/35~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/161~
- [x] ~https://github.com/sitmun/sitmun-viewer-app/issues/37~
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/179~
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/138~ seems fixed
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/148~ seems fixed 
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/135~ seems fixed 
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/133~ not specific context provided; related to [Dependabot alerts](https://github.com/sitmun/sitmun-admin-app/security/dependabot). Superseded by [#158](https://github.com/sitmun/sitmun-admin-app/issues/158)
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/55~ should have been closed
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/43~ was marked as wontfix 
- [x] ~https://github.com/sitmun/sitmun-admin-app/issues/7~ was a non finished task  
- [x] ~https://github.com/sitmun/sitmun-viewer-app/issues/18~ was a finished task  
- [x] ~https://github.com/sitmun/sitmun-viewer-app/issues/5~ was an invalid task 
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/96~ was implemented
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/21~ was implemented
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/138~ was implemented 
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/100~ is obsolete
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/139~ was partially implemented; oracle won't be implemented
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/144~ was partially addressed
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/149~ was implemented
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/161~ was won't fix
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/162~ was won't fix   
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/169~ was invalid 
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/170~ was won't fix
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/175~ can be considered done
- [x] ~https://github.com/sitmun/sitmun-backend-core/issues/178~ was done

# Future

These issues are for SITMUN 3 1.1:

- **Monitoring** https://github.com/sitmun/sitmun-backend-core/issues/25
- **Bulk edition** https://github.com/sitmun/sitmun-admin-app/issues/33
- **Enhanced proxy** https://github.com/sitmun/sitmun-backend-core/issues/180
